### PR TITLE
First attempt at a build script for translations

### PR DESCRIPTION
**Pull request by deanc**
Not sure exactly _how_ you want to handle this building, but this should be a start. Let me know how to proceed. I'm not fluent in Finnish so I'd need some help with the translations too - but let's get the code in place and then the translations can be taken care of by whomever.

### CODE REVIEW

**Comment by jareware** [comment]
This looks like a great start! I'll try to take a closer look tomorrow!

**Comment by EsaMakinen** [comment]
Looking good. We’ll get the translations done when there are placeholders for questions.

**Comment by deanc** [comment]
Hi @EsaMakinen - what do you mean by placeholders for questions?

**Comment by deanc** [comment]
Hi @jareware - converting to TS will be pretty easy, but the problem with this current setup as you have it as that the bundle is not injected into any other HTML file than index.html. I'm not sure how to solve that.

**Comment by EsaMakinen** [comment]
@deanc Sorry, bit vague. I was trying to say that when translations.json has all the text that needs to be translated - questions, buttons, after input -texts, etc - I’ll ask someone to do the proper translations. Also I’m now thinking that we should get the privacy info translated. 

And lets not go there yet, but swedish version of the embed would also be great.

**Comment by deanc** [comment]
Hi @EsaMakinen once @jareware can help find a solution for my question above it will be trivial to finish up adding keys for all the translations and getting it into other languages. I might suggest going one step further and considering translations for Arabic and Russian too. There are larger groups of people in these communities who have access to no media right now. Of course, you then need to a find a way to reach them using HS.fi too :)

**Comment by deanc** [comment]
@EsaMakinen I sent some feedback to HS directly on this. I appreciate the effort and open-ness of the HS datadesk in these times, but I think for this to have an impact it would require some changes from the top in approving some general journalism in other languages during these times:

This is the email I sent:

> Might it be worthwhile, during these challenging times - which we haven't seen since the Winter War to make your reporting on the crisis a little more diverse.
I'm currently working with the folks at Futurice and HS.fi data desk to try and get the symptom radar translated into English:
https://github.com/futurice/symptomradar/issues/118

> This, of course, will all not be worthwhile if you don't try and reach out to those communities. Might now, more than ever, be the time to diversify and try and translate some of your articles into other languages to engage with, and help these communities. Currently yle is the only media outlet translating any media coverage of covid-19 into English.

**Comment by jareware** [comment]
>the bundle is not injected into any other HTML file than index.html

Ah, indeed! As might be evident, we've put this together in a bit of a rush, and that shows in the state of CI/CD automation (or lack thereof).

Let me take a stab.

**Comment by deanc** [comment]
@jareware My advice would be to either drop CRA entirely for this as you're not using any react features, or switch over to react (+1) to make future changes easier. Adding react-18next would have been quite trivial. I can imagine the pressures your team was under to get this out in time :)

**Comment by deanc** [comment]
@jareware Seems this is not possible with CRA:
https://stackoverflow.com/a/57348468/775007

Maybe we could go back to a simple solution for now like: https://wangchujiang.com/translater.js/

Unless someone your side wants to undertake rewriting this app back to react or gatsby/next :)

**Comment by jareware** [comment]
@deanc I have a fix but I can't push it to your branch because it's on your fork.

I'll re-create the PR if you don't mind?

**Comment by deanc** [comment]
Sure, but then I can't push to yours :D?

**Comment by jareware** [comment]
No need; it's on master already! :joy: 

Thanks so much for your help @deanc!

**Comment by EsaMakinen** [comment]
Indeed, thank you!

**Comment by jareware** [comment]
> drop CRA entirely for this as you're not using any react features

True, but then someone would need to set up a bespoke webpack config for us... and using the one from `react-scripts` was just faster at the time. :sweat_smile: 

> or switch over to react (+1) to make future changes easier

We actually started our prototyping on pure CRA, but in the interest of performance (our embed gets a lot of hits and needs to load fast) switched to a more "traditional" setup. The embed is quite simple after all, and React would add a lot of weight.

**Comment by deanc** [comment]
Just for my own knowledge, what was the solution to inject the webpack bundle into the other html files?

**Pull request merged**
