### PR TITLE
Unify ts versions

### PR DESCRIPTION
**Pull request by olpeh**

### CODE REVIEW

**Comment by jareware** [comment]
Oh, I see:

```
$ unzip -l backend/dist/backend-lambda.zip | head -n 10
Archive:  backend/dist/backend-lambda.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2020-03-30 01:22   backend/
        0  2020-03-30 01:22   backend/src/
        0  2020-03-30 01:22   backend/src/core/
     9688  2020-03-30 01:22   backend/src/core/postalCode.js
     2259  2020-03-30 01:22   backend/src/core/main.js
     2616  2020-03-30 01:22   backend/src/index.js
        0  2020-03-30 01:22   common/
```

We should be packaging so that `backend/src/` is the root of the zipfile.

**Comment by jareware** [comment]
...but how does that work with the `common` package again. :man_facepalming:

**Comment by jareware** [comment]
Hmm, I wonder if we should now revisit this along with #132, 59b73a1, and #140 in a new PR?

**Comment by olpeh** [comment]
> Hmm, I wonder if we should now revisit this along with #132, [59b73a1](https://github.com/futurice/symptomradar/commit/59b73a1ff5fc0cf6f2276b5008b6d7d4484253bb), and #140 in a new PR?
Yeah, that sounds like a good idea. I think we can close this.

**Pull request closed without merging**
